### ISSUE TITLE
alguna posibilidad de reemplazar el comando print ?

### ISSUE THREAD

**Issue by matiazar** [dewetbaumann/dart-print-map#1]
Hola! como estas? muy lindo paquete, pero no habra alguna forma de reemplazar el comando print? para no tener que escribirlo de otra forma, o no tener que modificar todos los print que uno tiene en el proyecto?

gracias por el aporte!!

**Comment by dewetbaumann** [comment]
> 

La idea del package no es remplazar al print de Dart, ya que este solo sirve para imprimir datos de tipo ```Map<dynamic, dynamic>```, pero pensándolo no seria una mala idea hacer un print para datos de tipos string, y poder personalizar el color de salida. 

Respondiendo tu pregunta, podrías remplazar los print en tu proyecto reasinganando la importación del package con la palabra reservada `as`, te dejo un ejemplo:

```dart
import 'package:print_map/print_map.dart' as print; 

print.printMap(JSON);
```
